### ISSUE TITLE
Park showing as building

### ISSUE THREAD

**Issue by bcamper** [mapzen/vector-datasource#834] opened 2016-05-20 14:59 UTC
* **What did you see?**

The Olympic Sculture Park in Seattle is showing as a building, but it is only a park (it has some buildings within it).

* **What did you expect to see?**

It should only render as a park, and not be included in the `buildings` layer.

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

http://www.openstreetmap.org/way/239782410
http://tangrams.github.io/bubble-wrap/#17.675/47.61578/-122.35529

* **Screenshot?** _Props for animated gifs._

![screen shot 2016-05-20 at 10 54 34 am](https://cloud.githubusercontent.com/assets/16733/15431839/9ab528b2-1e79-11e6-9e20-445d775dd1d4.png)

**Comment by bcamper** [comment] 2016-05-20 15:02
Possible dupe of https://github.com/mapzen/eraser-map/issues/564?

**Comment by nvkelso** [comment] 2016-05-20 15:17
Can you help debug this more, please? It only seems to happen at zoom 16+, and I believe happens for *all* features from the landuse layer. Is this coming from the server or happening on the client?

**Comment by nvkelso** [comment] 2016-05-20 15:17
Yeah, and of another in Refill.

**Comment by rmarianski** [comment] 2016-05-20 15:24
It exists in *both* the `buildings` and `landuse` layers. It's showing up in the `buildings` layer because there is an `addr_housenumber` tag on it.

http://vector.mapzen.com/osm/all/16/10493/22885.json

**Comment by zerebubuth** [comment] 2016-05-20 15:35
Ah, do we need to convert polygons with `kind:address` to points in the post-processor?

**Comment by nvkelso** [comment] 2016-05-20 16:04
Looks like this is a regression over v0.9 tiles where only the landuse polygon is present:

- http://vector.mapzen.com/osm/v0.9/all/16/10493/22885.json

What might have caused the regression? 

I'm not sure we should include addresses on large landuse polygons at all as point features – they're always going to be under the land use's label, and the address name is going to be at a generic placement probably far from where the nearest building is. 

If the fix is simple, can we roll a v0.10.3 release and enqueue affected zoom 16 tiles?

**Comment by nvkelso** [comment] 2016-05-20 16:07
Verified potential fix to excluding address polygons in Bubble Wrap style locally and it fixes the problem. (We should fix tiles, not all the many style variants.)

**Comment by zerebubuth** [comment] 2016-05-20 16:17
The regression was caused by the YAML not filtering by geometry type. Previously, we'd explicitly pulled address points from `planet_osm_points` in the query, but the way it's structured now it also picks up polygons with address tags on them.

I think we _should_ be generating an address point (effectively, a label placement) for these polygons - but we shouldn't be outputting them as polygons in the buildings layer.

A secondary bug is that the style must be drawing all polygons in the `buildings` layer as buildings, regardless of whether they have `kind:building` or `kind:address`.

**Comment by bcamper** [comment] 2016-05-20 16:39
I'd prefer that a naive style be able to assume that any *polygons* in the
buildings layer are safe to render without additional filtering (for
simplicity and client filtering speed I think this is reasonable). (Of
course filtering on properties for other style options may be desirable.)

**Comment by nvkelso** [comment] 2016-05-20 16:44
Agree with @bcamper that the style should be naive about this (assume polygon features in the buildings layer are buildings only). Fixing the tiles is easier than fixing all our style variants on our CDN and all the apps in the wild and 3rd party styles we don't know about.

I'm fine generating an address point for a building (it's labeling where the address is), but not for a landuse feature (arguably we should strip the address completely from the landuse polygon attributes).

**Comment by zerebubuth** [comment] 2016-05-20 16:59
Why can only buildings have addresses?

When the address location (main entrance, mailbox, whatever) is known accurately, then it should be mapped as a point. In this situation it seems that the address is known, but not the appropriate point to locate it, in which case it seems reasonably to add it to the polygon and generate a representative point for it.

Should we consider moving the address points and building labels out into their own `addresses` layer so that we can skip the geometry type checks?

**Comment by nvkelso** [comment] 2016-05-20 17:47
Let's get this PR in ASAP, and deploy next week.

**Comment by nvkelso** [comment] 2016-05-23 22:30
Fixed in `prod` using v0.10.3 tile stack.

**Closed by nvkelso** 2016-05-23 22:30 UTC
Labels: bug, send to prod
