### ISSUE TITLE
No `height` property generated for `building:levels`

### ISSUE THREAD

**Issue by bcamper** [mapzen/vector-datasource#806] opened 2016-05-10 17:28 UTC
* **What did you see?**
`building:levels` tag in OSM did not result in a `height` property being generated in tile.

* **What did you expect to see?**
My understanding was that we were synthesizing a `height` property in tiles (where one doesn't already exist) from other data including `building:levels`.

* **What map location are you having problems with?** _City and country are helpful, as well as tile coordinates or latitude / longitude._  

http://tangrams.github.io/bubble-wrap/#17/37.25730/127.05379
https://www.openstreetmap.org/way/161390790#map=18/37.25823/127.05604
https://vector.dev.mapzen.com/osm/all/16/55897/25449.topojson?api_key=vector-tiles-HqUVidw

```
buildings: {
   type: "GeometryCollection",
   geometries: [
      {
         type: "Polygon",
         properties: {
            building_levels: "25",
            kind: "Samsung tower 3",
            name: "R5",
            area: 46363,
            sort_key: 475,
            landuse_kind: "industrial",
            source: "openstreetmap.org",
            min_zoom: 13,
            id: 161390790
         },
      ...
```

**Comment by bcamper** [comment] 2016-05-10 17:30
For example see https://github.com/mapzen/vector-datasource/blob/650353bc0bca603fd3d5f356eb3b134d9a5c84d0/data/functions.sql#L489-L514

**Comment by zerebubuth** [comment] 2016-05-10 17:34
Ooops, thanks for pointing that out. Looks like we dropped the `:` earlier and didn't update [downstream transforms](https://github.com/mapzen/TileStache/blob/6c75a67ae8a39cbc4926cd87c4596f27a0b04141/TileStache/Goodies/VecTiles/transform.py#L165)?

**Comment by nvkelso** [comment] 2016-05-10 19:19
Ooops, this is a regression over v0.9 tiles. Moving to new v0.10.2 bug fix release.

**Closed** 2016-05-11 18:45 UTC
