### ISSUE TITLE
Some binary tiles don't seem to work

### ISSUE THREAD

**Issue by zeesource** [mapzen/vector-datasource#323] opened 2015-10-21 19:26 UTC
Hi,

 Thank you for providing the vector tile service. This is very useful for getting our feet wet with vector tiles.
 
 This is not really an issue, but a question.

 I was experimenting with the mapnik-vector-tile project on GitHub and was able to render a tile that is present in their examples/data folder, but could not render a tile obtained through your service.

 I am wondering if the binary tiles from your service are compatible with the the latest code from mapnik-vector-tile, using mapping 3.0.5?

 Thanks

**Comment by zeesource** [comment] 2015-10-21 19:29
Oops..sorry. Just got it to work. Never mind.

**Comment by zeesource** [comment] 2015-10-21 21:23
Re-opening...seem to be able to render (1) below but not (2).

1. http://vector.mapzen.com/osm/roads/14/8716/8015.mvt

but cannot render:

2. http://vector.mapzen.com/osm/roads/13/4091/2724.mvt

tileinfo --verbose also does not seem to give good geometries for (2)

**Comment by jamesbursa** [comment] 2015-11-11 18:10
I'm seeing what looks like the same bug. I have only seen it when requesting specific layers, not with "all", and at zooms of 18 or lower.

Here is an example (I chose a tile that has just one building):

```
$ curl -o buildings_18_74972_100295.mvt 'https://vector.mapzen.com/osm/buildings/18/74972/100295.mvt?api_key=...'
$ curl -o all_18_74972_100295.mvt 'https://vector.mapzen.com/osm/all/18/74972/100295.mvt?api_key=...'

$ tileinfo --verbose buildings_18_74972_100295.mvt
message: appears not to be compressed
layer: buildings
  version: 2
  extent: 4096
  keys: landuse_kind,id,area
  values: park,66418986,474
  feature: 0
    type: Polygon
    tags: 0,0,0,0,0,0
    geometries: 9,153,8114,194,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15  

$ tileinfo --verbose all_18_74972_100295.mvt
message: appears not to be compressed
layer: water
  ...

layer: buildings
  version: 2
  extent: 4096
  keys: landuse_kind,id,area
  values: park,66418986,474
  feature: 0
    type: Polygon
    tags: 0,0,0,0,0,0
    geometries: 9,1385,7316,194,64,19,31,99,17,53,100,31,85,271,5,17,180,57,760,245,103,327,25,81,47,147,1,5,562,181,34,108,240,758,16,46,73,24,21,67,439,142,140,438,267,86,387,126,493,158,75,235,15

layer: places
  ...
```

Note the correct geometries in the "all" file, but 0s in the "buildings" file. The length of the geometry matches between the two files.

Tileinfo is from https://github.com/mapbox/mapnik-vector-tile, but the same problem is visible directly in the protobuf using:

```
protoc ./node_modules/vector-tile/proto/vector_tile.proto --decode=tile < buildings_18_74972_100295.mvt
```

**Comment by rmarianski** [comment] 2015-11-24 16:55
This should be fixed now. Do you mind verifying if it works for you now?

**Comment by zeesource** [comment] 2015-12-01 18:56
Sorry, I tore down my test environment for this a while back, so unable to test. Perhaps @jamesbursa can test. If really need to, I can set up another environment.

**Comment by nvkelso** [comment] 2015-12-04 19:06
Tiles Meeting: Closing this for now since it's on prod. If it's an issue again, please comment here and we either reopen or create new issue.

**Closed by nvkelso** 2015-12-04 19:06 UTC
Labels: bug, loe high

**Comment by jamesbursa** [comment] 2015-12-07 23:30
Sorry for the delay. I can confirm that the bug is fixed. Thanks!

I tested it as in my comment above, and by rendering the layer using Mapbox GL.

**Comment by nvkelso** [comment] 2015-12-08 05:20
Wonderful to hear, thanks for verifying!
