### ISSUE TITLE
REGRESSION: country & state tags suddenly no longer available at z0-z8

### ISSUE THREAD

**Issue by musicformellons** [mapzen/vector-datasource#260] opened 2015-09-27 12:16 UTC
I think my stylesheet did not change but suddenly countrynames no longer appear at z0 - z3. They do appear at z4 and higher. Something changed on you side!?

**Comment by nvkelso** [comment] 2015-09-27 16:07
Sorry about that, will check Monday.

**Comment by nvkelso** [comment] 2015-09-28 22:00
We were incorrectly double packing the `place` layer with features from OSM and Natural Earth, leading to duplicate populated places (city) points. We solved that in a825aa6eae8092a3a43d3d0fea3b01ee312dc2d2 by transitioning from Natural Earth to OSM at zoom 9 (instead of unioning them always). But that's created a problem because we're now missing  `country` and `state` points in the `places` layer from zoom(0-9), a regression.

**Comment by musicformellons** [comment] 2015-09-29 07:11
I see, thanks.

**Comment by nvkelso** [comment] 2015-09-30 04:12
Fixed in master, waiting to send to dev machine. Will likely show up in prod over the weekend.

**Comment by nvkelso** [comment] 2015-10-02 01:40
Nevada's back:

<img width="496" alt="screen shot 2015-10-01 at 18 40 14" src="https://cloud.githubusercontent.com/assets/853051/10237798/e9f159e2-686b-11e5-8235-83f8c99d8e6f.png">

**Closed** 2015-10-20 17:08 UTC
